# .github/workflows/docker-publish.yml
name: Build and Push Docker Image to GitHub Container Registry

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run on a fresh Ubuntu VM

    permissions:
      contents: read # Allow reading the repository contents
      packages: write # Allow writing to GitHub Packages (GHCR)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for advanced features

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io # Specify the GitHub Container Registry
          username: ${{ github.actor }} # Use the GitHub actor (workflow user) as username
          password: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN for authentication

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # The build context is the root of your repository
          push: true # Push the image to GHCR
          tags: |
            ghcr.io/${{ github.repository }}/tamil-blasters-addon:latest
            ghcr.io/${{ github.repository }}/tamil-blasters-addon:${{ github.sha }} 
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max # Cache layers for future builds
