# .github/workflows/docker-publish.yml
name: Build and Push Docker Image to Docker Hub

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for advanced features

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Use GitHub secret for Docker Hub access token (recommended)

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # The build context is the root of your repository
          push: true # Push the image to Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tamil-blasters-shows:latest 
            ${{ secrets.DOCKER_USERNAME }}/tamil-blasters-shows:${{ github.sha }} 
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max # Cache layers for future builds
